server:
  port: 8081

spring:
  application:
    name: admin-microservice

  datasource:
    url: jdbc:postgresql://localhost:5432/medloop_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/medloop
          jwk-set-uri: http://localhost:8080/realms/medloop/protocol/openid-connect/certs

logging:
  level:
    root: INFO
    com.medloop: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  cors:
    allowed-origins: http://localhost:4200
  jwt:
    auth:
      converter:
        resource-id: admin-service
        principal-attribute: preferred_username
