spring.application.name=patient-service
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/XEPDB1
spring.datasource.username=system
spring.datasource.password=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
server.port=8081

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Disable Config Server (we're not using it for now)
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Actuator endpoints for monitoring
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
